site_name: Metsäkoetietojärjestelmän QField PoC 
copyright: 'Tekijä: <a href="info@gispo.fi">Gispo Suomi Oy</a>'
nav:  
  - Koti: 0_index.md
  - 1. Alkuvalmistelut: 1_alkuvalmistelut.md
  - 2. Projektin vienti QFieldiin: 2_vienti.md
  - 3. QFieldin peruskäyttö: 3_qfield.md
  - 4. Mktj-PoC:n käyttö: 4_mktj.md
  - 5. QFieldistä QGISiin: 5_qfieldista_qgissiin.md
use_directory_urls: false
theme: readthedocs
